/*
 * Auto-generated by ./build on Thu Aug 16 19:26:40 EDT 2018
 */
#ifndef BUILD_H
#define BUILD_H
static const string VERSION ="libdixie Version 1.0";
static const string SERIAL  ="180816192640";
#endif
