/*
 * Auto-generated by ./build on Sat Mar 9 10:54:20 EST 2019
 */
#ifndef BUILD_H
#define BUILD_H
static const string VERSION ="libdixie Version 1.0";
static const string SERIAL  ="190309105420";
#endif
