#!/bin/sh
############################
# build libdixie.a 
############################
#
 
if g++ -I$HOME/include -I. DixieTerminal.cpp -c; then
    echo "DixieTerminal Object created..."
    if ar cr $HOME/lib/libdixie.a DixieTerminal.o; then
        echo "DixieTerminal.o added to $HOME/lib/libdixie.a library..."
        if g++ test.cpp -I$HOME/include -I. -L$HOME/lib -ldixie -o test; then
            echo "Build complete -- run ./test to verify"
        else
            echo "***ERROR compiling test.cpp"
        fi
    else
        echo "***ERROR adding to library build terminated "
    fi
else
    echo "***ERRORS in DixieTerminal.cpp build terminated "
fi

 
