/*
 * Auto-generated by ./build on Tue Nov 14 17:11:25 EST 2017
 */
#ifndef BUILD_H
#define BUILD_H
static const string VERSION ="DixieMenu Version 1.0";
static const string SERIAL  ="171114171125";
#endif
